출처입니다.  
https://www.kaggle.com/competitions/big-data-analytics-certification-kr-2023-5th/

In [45]:
import pandas as pd
import math
from scipy.stats import skew
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from lightgbm import LGBMRegressor
from xgboost.sklearn import XGBRegressor
# 난수 값
rdst = 10

In [47]:
# [가격 예측] 중고 자동차
# 자동차 가격을 예측해주세요!
# 예측할 값(y): price
# 평가: RMSE (Root Mean Squared Error)
# data: train.csv, test.csv

df = pd.read_csv("./data/csv/train_5회유형.csv")

# print(df.nunique())   # 컬럼별 값 개수 확인

df = pd.get_dummies(df)    # object 유형 onehotencoding

for i in range(6) : 
    result = skew(df.iloc[:,i])
#     print(result)

X = df.drop("price", axis=1)  # 독립 변수
y = df["price"]   # 종속 변수

## train_test_split ##
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=rdst)

## minmaxsccaler ##
mmsc_x = MinMaxScaler()
mmsc_y = MinMaxScaler()

mmsc_x.fit(X_train)
mmsc_y.fit(y_train.to_frame())

X_train_sc = mmsc_x.transform(X_train)
X_test_sc = mmsc_x.transform(X_test)

y_train_sc = mmsc_y.transform(y_train.to_frame()).reshape(-1)
y_test_sc = mmsc_y.transform(y_test.to_frame()).reshape(-1)

# print(X_train_sc.shape,X_test_sc.shape,y_train_sc.shape,y_test_sc.shape)
# print(y_train_sc)

## model_train_randomforest ##

rf = RandomForestRegressor(n_estimators=100)

rf.fit(X_train_sc, y_train_sc)

y_pred = rf.predict(X_test_sc)

print("모델의 rmse =", round(math.sqrt(mean_squared_error(y_test_sc, y_pred)),6))
print("모델의 r2 score =", round(math.sqrt(r2_score(y_test_sc, y_pred)),4))

y_pred_act = mmsc_y.inverse_transform(y_pred.reshape(-1,1))

print(y_pred_act)

print("---------------------")

## model_train_linear ##

lr = LinearRegression()

lr.fit(X_train_sc, y_train_sc)

y_pred_lr = lr.predict(X_test_sc)

print("모델의 rmse =", round(math.sqrt(mean_squared_error(y_test_sc, y_pred_lr)),6))
print("모델의 r2 score =", round(math.sqrt(r2_score(y_test_sc, y_pred_lr)),4))

y_pred_lr_act = mmsc_y.inverse_transform(y_pred_lr.reshape(-1,1))

print(y_pred_lr_act)

print("---------------------")

## model_train_lightgbm ##

lg = LGBMRegressor(n_estimators=100)

lg.fit(X_train_sc, y_train_sc)

y_pred_lg = lg.predict(X_test_sc)

print("모델의 rmse =", round(math.sqrt(mean_squared_error(y_test_sc, y_pred_lg)),6))
print("모델의 r2 score =", round(math.sqrt(r2_score(y_test_sc, y_pred_lg)),4))

y_pred_lg_act = mmsc_y.inverse_transform(y_pred_lg.reshape(-1,1))

print(y_pred_lg_act)

print("---------------------")

## model_train_xgb ##

xg = XGBRegressor(n_estimators=100)

xg.fit(X_train_sc, y_train_sc)

y_pred_xg = xg.predict(X_test_sc)

print("모델의 rmse =", round(math.sqrt(mean_squared_error(y_test_sc, y_pred_xg)),6))
print("모델의 r2 score =", round(math.sqrt(r2_score(y_test_sc, y_pred_xg)),4))

y_pred_xg_act = mmsc_y.inverse_transform(y_pred_xg.reshape(-1,1))

print(y_pred_xg_act)


모델의 rmse = 0.03658
모델의 r2 score = 0.9577
[[20035.41]
 [ 7885.19]
 [ 7469.  ]
 ...
 [16890.6 ]
 [15988.8 ]
 [ 8966.97]]
---------------------
모델의 rmse = 0.048849
모델의 r2 score = 0.9231
[[20210.26855469]
 [ 9956.27685547]
 [ 7877.12646484]
 ...
 [17592.42919922]
 [14993.49121094]
 [ 8765.49072266]]
---------------------
모델의 rmse = 0.035278
모델의 r2 score = 0.9607
[[19011.32978223]
 [ 7745.30267542]
 [ 7113.21507152]
 ...
 [19191.68326179]
 [16379.98654248]
 [ 8815.46699198]]
---------------------
모델의 rmse = 0.034397
모델의 r2 score = 0.9627
[[19503.656 ]
 [ 7932.813 ]
 [ 7119.8203]
 ...
 [17898.459 ]
 [15482.829 ]
 [ 8932.407 ]]
